---
title: "Commercial catch expansion"
author: ""
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Commercial catch expansion}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# General overview

1. From "RAW" landings data (mv_cf_landings, AA t/s tables) we need to:

* Assign all missing areas and/or assign all trips to an EPU
* 10 min square designations exist in mv_cf_landings from 1994 onward. (Sean, Mike presentation in 2010 "Ecosystem – Based Fishery Management for the New England Fishery Management CouncilPart Deux: Spatial Considerations" shows landings by gear type from 1998-2009.Expanding to earlier years might not be possible.) So then how get landings to EPU for earlier years? If use trip characteristics to do this we are assuming the fishery has remained somewhat constant over time. Is this realistic? What to do?
* missing gear type can be dealt with in length expansion. (Assume unknowns have proportional make up of the known gear types)
* Aggregate landings by year, quarter, gear, market category, stat area assigned to proper ecoregion:

2. From "RAW" length data (mv_cf_len, LEN AA tables) we need to 

* Determine the number of length samples and total number of lengths by year, quarter, gear, market category, stat area assigned to proper ecoregion. (G.S -"Summarize biological samples by year, gear, quarter, market category, stat area. Compare to landings.")
* Assign AREA to EPU. (May need to try and link "trip" to landings data after EPUs assigned to determin EPU)

3. Then merge both data sets. This will be the starting dataset needed for the following rules by G.S.

4. Now start to  *Combine* cells to increase sample sizes or *interpolate* individual missing cells? 

# Rules of aggregation

To determine "similar length distributions" we could use the two sample Kolmogorov-Smirnov test. The test compares empirical CDF's. We would construct the empirical CDF from the histogram of length's (over all samples) at 1 cm intervals. 



In many stock assessments each year may result in a different level of aggregation (i.e quarters, semesters or different gear types).
For the first pass here we will use the same aggregation level for all years. Maybe a good exercise to compare results.

(Within each year t:)

## Combine:
* Are there *gear* types with total landings greater than 0 but total sample sizes less than *X*?  
    + if YES: 
        - Combine gear types (explore to see if combined lengths similar) to increase sample size  
        - or Ignore and continue (add to total at the end).  
    + if NO: Count your blessings and continue.  
* Are there *market categories* (will need to assign to an ordinal scale) with total landings greater than 0 but sample sizes less than *X*? (after combining gears)  
	  + if YES: combine market categories with similar length distributions. 
	  + if NO : Count your blessings and continue.  
* Are there *quarters* with landings but sample sizes less than *X*?  
	  + if YES: Create semesters?  
	  + if NO: Count your blessings and continue.  
* Are there *strata* with landings but sample sizes less than *X*?  
	  + If YES: define groups of similar strata  
	  + If NO: Count your blessings and continue.  
	  
* Interpolate remaining holes.  
	  + Select length within year/market category from adjacent strata or strata group (after determining if appropriate).  
	  + Select length within year/market category from adjacent quarter or semester (after determining if appropriate).  
	  + Select length within year/market category from adjacent year (after determining if appropriate).  
* If unclassified market category and no other information available:  
	  + Combine market category samples to create an unclassified  
	  + Use appropriate observer length samples to apply to unclassified.  
* If holes remain  
	  + Calculate ratio of sampled to un-sampled landings and expand total length frequency such that expanded sample weight equals total landings weight for year t.





## Interpolate only:
If examination of sample matrix shows only sporadic missing cells with landings but sample sizes less than *X*:  

* Samples by year/gear/quarter/stat area/market category  
	  + Nearest stat area within market category/quarter/gear/year  
	  	  + Keeping year/market category constant:  
	  	  	  + Adjacent quarter/ same stat area  
	  	  	  	  + Adjacent quarter/ any stat area within ecoregion  
	  	  	  	  	  + Adjacent semester/matching stat area  
	  	  	  	  	  	  + Adjacent semester/ any stat area within ecoregion  
                            +  If lengths by gear are similar: Alternative gear/same quarter/stat area	
	  	  	  	  	  	  	  	  + Alternative gear/same quarter/any stat area
	  	  	  	  	  	  	  	  	  + Alternative gear/semester/same stat area
	  	  	  	  	  	  	  	  	  	  + Alternative gear/semester/any stat area
	  	  	  	  	  	  	  	  	  	  	  + No options- extrapolate to total

*Or combination of both approaches*

## Vocabulary
Definitions to think about.
* Area - could be stock area or EPU
	  + Stat area - smallest unit that the landings are reported to 
	  + Stock area - stock assessment footprint (combined stat areas)
	  + EPU - ecological production unit
* Time - quarter, semester, annual	
	  + Quarter - 3 month
	  + Semester - 6 month
	  + Annual - 12 month
* Length - market categories, cm, 
	  + Market categories - could vary over port, time, 


# Discards

Need to deal with discards in a similar fashion.
It seems that Susan Wigley has a SAS script that most/some stock assessment scientists use to help with this.
Edit: Spoke to Susan Wigley she says that they will have all of the discard estimates over time for all of the species in a database similar to that of the landings, length, age databases. This will make life heck of a lot simpler for us.
			
	


