---
title: "Data Notes"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## ADIOS!

This is the database that the population dynamics (Pop Dy) branch use for their stock assessments.  

* Access the online [GUI](file://155.206.139.2/home0/pdy/pub/STOCKEFF/ADIOS/website/webfiles/ADIOS_homepage.html)

* Read the [DOCUMENTATION](file://155.206.139.2/home0/pdy/pub/STOCKEFF/ADIOS/ADIOS_CF/website/webfiles/ADIOS_technical_documentation.pdf)

The landing portion are stored in the Stockeff.MV_cf_Landings materialized view. (This is equivalent to AA Trip and AA Species tables joined). Each record represents trip and species data for a specific landed species. A trip will appear as many times as there are landed species in that trip

* MV_CF_LANDINGS  - (WOLANDT/S,WODET/S, CFDETT/S tables combined)

* MV_CF_AGE - (WOAGE, CFAGE AA tables combined)

* MV_CF_LEN (WOLEN, CFLEN AA tables combined)

### Statistical Area

In the database there are:

* 35,515,060 records
* 6,913,365 record (20%) still have unknown area designation (AREA = '000')

Pop Dy branch will assign these records to areas based on the species of interest. Of course this means that a trip could be assigned to several different areas depending on the species of interest. The algorithm for assigning the area is run "behind the scenes" when a scientist using the web GUI makes a request for data.


### Latitude and Longitude

* 35,515,060 records
* 14,288,139 records (40%) have valid GIS_LAT, GIS_LON
* 21,227,636 records (60%) where GIS_LAT, GIS_LON is null

* 1,952,157 records (5%) where LAT, LON are null 
* 1,482,958 records (4%) where LAT or LON are '00'
* 17,791,806 records (50%) where LAT or LON are '0000'

#### Trip level records

Use link field as the unique identifier

* 15,774,961 unique trips (15,776,348 in AA tables -> 1387 trips removed)
* 2,596,744 records (16%) have valid GIS_LAT, GIS_LON

* when comparing the AA tables by year and ADIOS by year 




There is a TENMSQ field but only included from 1994+

Allocation rules:

1. All trips WITH missing AREA (='000') need to be assigned to an AREA

1.  If most of the GIS_LAT and GIS_LON fields contain valid entires we can allocate these TRIPS to an EPU.

1. For those that do not (hopefully only 10%) we will need to allocate these trips to an EPU based on the AREA they fished.

1. If they fished in an AREA that is entirely within an EPU, we can allocate to that EPU

1. Otherise the AREA straddles multiple EPUs so we will need to look at all trips already in associated with that AREA and allocate to an EPU based on most similar trips. HOW DO THIS?



### Market Category

Simplified to categories based on the species (Looking for definitions)

eg Cod -> "UN", "LG", "MK", "SK"


## Questions for Stock Assessment Scientists

1. For areas defined as '000' (post AA table creation). How do they deal with them?
For example: Does the scientist pull all cod data then deal with the missing areas from this reduced data set or are all missing areas dealt with THEN cod data are pulled?

1. Is this consistent for all scientists? and is the method of dealing with missing area  designations consistent?

1. If everyone is using ADIOS then what are the scripts in the background (from the GUI) doing to answer these questions?
